name: Deploy to Cloud Run

on:
  push:
    branches:
      - simulation
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: watt-horizon  

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        IMAGE_NAME="gcr.io/watt-horizon/openems-edge"
        docker build -t $IMAGE_NAME -f tools/docker/edge/Dockerfile .
        docker push $IMAGE_NAME

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy openems-edge \
          --image $IMAGE_NAME \
          --region europe-central2 \
          --platform managed \
          --allow-unauthenticated
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
