name: Deploy to Cloud Run

on:
  push:
    branches:
      - simulation
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: "watt-horizon"
        install_components: "beta"
        
    - name: Verify Authentication and Permissions
      run: |
        gcloud auth list
        gcloud projects describe watt-horizon
        gcloud artifacts repositories list --location=europe-central2

    - name: Configure Docker
      run: gcloud auth configure-docker europe-central2-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        IMAGE_NAME="europe-central2-docker.pkg.dev/watt-horizon/openems-edge/openems-edge:latest"
        docker build -t $IMAGE_NAME -f tools/docker/edge/Dockerfile .
        docker push $IMAGE_NAME

    - name: Deploy to Cloud Run
      run: |
        IMAGE_NAME="europe-central2-docker.pkg.dev/watt-horizon/openems-edge/openems-edge:latest"
        gcloud run deploy openems-edge --image $IMAGE_NAME --region europe-central2 --platform managed --allow-unauthenticated
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
